language: java
jdk:
- oraclejdk9	
sudo: required
addons:
  postgresql: "9.6"
services:
- postgresql
before_script:
  - psql -c "CREATE USER chapay SUPERUSER;" -U postgres
  - psql -c " alter user chapay createdb;" -U postgres
  - psql -c "create database gamedb;" -U postgres
  - psql -c "drop table if exists flyway_schema_history;" -U postgres
  - psql -c "grant all on database gamedb to chapay;" -U postgres
